/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tang_smartupdate_PatchUtil */

#ifndef _Included_com_tang_smartupdate_PatchUtil
#define _Included_com_tang_smartupdate_PatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tang_smartupdate_PatchUtil
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tang_smartupdate_PatchUtil_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
